### PR TITLE
remove `fs-cp` dependency

### LINKED ISSUE #19: remove `fs-cp`?
Why it is there? Everyone can add it and use it directly, if he want it. This also blocks using this package in plugins, like 

``` js
var bodyParsers = require('koa-body-parsers')
var koa = require('koa')
var app = koa()

app.use(function * () {
  bodyParsers(this)
})
.use(function * () {
  this.body = yield this.request.json()
})
```

for example - i need it this way, because I'm going to use it in plugin that wraps these things.

Fails to set `.save` on `app.context`

```
TypeError: Cannot set property 'save' of undefined
      at /home/charlike/dev/final/koa-better-body/node_modules/koa-body-parsers/index.js:18:22
      at Array.forEach (native)
      at Function.module.exports.Object.keys.forEach.Object.keys.forEach.Object.keys.forEach (/home/charlike/dev/final/koa-better-body/node_modules/koa-body-parsers/index.js:17:24)
      at Object.plugin (/home/charlike/dev/final/koa-better-body/index.js:21:11)
      at next (native)
      at Object.<anonymous> (/home/charlike/dev/final/koa-better-body/node_modules/koa-compose/index.js:28:12)
      at next (native)
      at onFulfilled (/home/charlike/dev/final/koa-better-body/node_modules/co/index.js:65:19)
      at /home/charlike/dev/final/koa-better-body/node_modules/co/index.js:54:5
      at Object.co (/home/charlike/dev/final/koa-better-body/node_modules/co/index.js:50:10)
```

### PR DESCRIPTION
**Pull request by tunnckoCore**
resolves #19

### CODE REVIEW

**Comment by coderhaoxin** [comment]
@tunnckoCore I only use node@4+, can you split `support node@0.12` to another PR?

@jonathanong what's your option for `0.12`?

**Comment by tunnckoCore** [comment]
I'm using this package in upcoming v2 (in a bit, I'm waiting this pr) of `koa-better-body`. And we need/want have support for 0.12. It's not serious to drop support for 0.12 because of the few variables and one arrow function. I hate such forces and non-logical moves - i'm not talking for this exactly case, in general. They doesn't do so special things and not worth using them here currently.

I was not going to add this commit, but it breaks my builds, so it's needed to me.

**Comment by coderhaoxin** [comment]
OK, but we can use `const` on 0.12, right? Why changed to `var`?

**Comment by tunnckoCore** [comment]
Actually, yes we can. Maybe I didn't realize that I'm changing them or my habits, nevermind. What's the point using `const` exactly, currently here? There's no point. 

I'm against using features and things (in general) because they are just there and because they exist.

**Comment by coderhaoxin** [comment]
> What's the point using const exactly

1. no need revert `const` to `var` again. It's noisy
2. they are constant indeed

**Comment by jonathanong** [comment]
won't be merging this PR in this form. please feel free to open a new one!

**Pull request closed without merging**
